---
- name: "小onfiguring the inetrouter"
  hosts: inetRouter
  gather_facts: true
  roles:
    - inetRouter
  become: true


- name: "小onfiguring centralServer"
  hosts: centralServer
  gather_facts: true
  roles:
    - centralServer
  become: true

  
- name: "小onfiguring centralRouter"
  hosts: centralRouter
  gather_facts: true
  roles:
    - centralRouter
  become: true

- name: "小onfiguring inetRouter2"
  hosts: inetRouter2
  gather_facts: true
  roles:
    - inetRouter2
  become: true
