---
- name: nmap
  yum:
    name: nmap
    state: present  

- name: Set sysctl params
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.conf
    ignoreerrors: yes
    reload: yes
  with_dict: "{{ sysctl_params }}"


- name: Disable default route for eth0
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: DEFROUTE=no
  notify: restartnet


- name: Routes in file 
  lineinfile:
    path: /etc/sysconfig/network-scripts/{{ item.routes_file }}
    create: yes
    regexp: ^{{ item.network }}
    line: '{{ item.network }} via {{ item.via }} dev {{ item.net_interface }}'
  loop:  
    - "{{ routes_params.centralRouter.eth2 }}"
    - "{{ routes_params.centralRouter.eth3 }}"


- name: Add gateway
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-{{ gateway.interface }}
    regexp: ^GATEWAY
    line: GATEWAY={{ gateway.ip }}
  notify: restartnet


- name: Copy file knock.sh 
  copy:
    src: knock.sh
    dest: /home/vagrant/knock.sh
    owner: vagrant
    group: vagrant
    mode: '0744'


- name: Reboot servers
  reboot: 
    msg: "Reboot initiated by Ansible"