---
- name: Set sysctl params
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.conf
    ignoreerrors: yes
    reload: yes
  with_dict: "{{ sysctl_params }}"


- name: Routes in file 
  lineinfile:
    path: /etc/sysconfig/network-scripts/{{ routes_params.inetrouter.routes_file }}
    create: yes
    regexp: ^{{ routes_params.inetrouter.network }}
    line: '{{ routes_params.inetrouter.network }} via {{ routes_params.inetrouter.subnet }} dev {{ routes_params.inetrouter.net_interface }}'
  notify: restartnet  


- name: Copy file 
  copy:
    src: iptables.rules
    dest: /etc/sysconfig/iptables
    owner: root
    group: root
    mode: '0600'
  notify: restartnet  

- name: Pass auth
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'
  notify: sshd restart


- name: Reboot server
  reboot: 
    msg: "Reboot initiated by Ansible"


- name: iptables-restore  
  shell: 'iptables-restore < /etc/sysconfig/iptables'