---
- name: epel-release
  yum:
    name: epel-release
    state: latest   


- name: install  nginx
  yum:
    name:  nginx
    state: present

- name: Disable default route for eth0
  lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
  notify: restartnet


- name: Add gateway
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-{{ gateway.interface }}
    regexp: ^GATEWAY
    line: GATEWAY={{ gateway.ip }}
  notify: restartnet


- name:  Enable nginx firewalld
  firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled


- name: Enable nginx service
  systemd:
      name: nginx
      state: started
      enabled: yes


- name: Reboot server
  reboot: 
    msg: "Reboot initiated by Ansible"